### ISSUE TITLE
Errors not show proper messages

### ISSUE THREAD

**Issue by umarjavedse** [saudslm/recharge-api-node#7] opened 2020-04-17 10:23 UTC
Hi @saudslm ,
I notice that issue after patch v1.1.1 released, before that http error send complete information of error but now just showing `name: 'HTTPError'`.
Please have a look on it because it is not possible to understand why API throw exception.
Thanks.

**Comment by umarjavedse** [comment] 2020-04-23 08:56
@saudslm 
Issue in error handling with GOT library you are using. Please have a look on it.
Thanks.

**Comment by saudslm** [comment] 2020-04-27 17:50
@umarjavedse 
Can you tell me how can I reproduce this? I am getting a full error object on my end.

**Comment by umarjavedse** [comment] 2020-04-27 18:56
@saudslm 
In v1.1.0 was working but after updating libraries errors not throwing full error object.
I tried to debug in library but in catch just getting  `name: 'HTTPError'` .

**Comment by saudslm** [comment] 2020-04-27 19:15
@umarjavedse 

I can access `e.response` object in catch block, in the latest version. Can you please check again?

**Comment by umarjavedse** [comment] 2020-04-27 19:22
@saudslm 
let me check

**Comment by saudslm** [comment] 2020-05-01 00:45
@umarjavedse 
Closing this for now, since it's working fine. I'll make sure to add it to the documentation.

**Closed by saudslm** 2020-05-01 00:45 UTC
